### ISSUE TITLE
OTP not sending

### ISSUE THREAD

**Issue by AnasAshir** [saran-surya/email_auth#11]
I am receiving the following error message. Any solution?

Email ID is valid
--This error is from the package--
XMLHttpRequest error.
--End package error message--

**Comment by BryanLeong99** [comment]
I have the same issue as well.

**Comment by divyansh1511** [comment]
I am also facing the same issue...

**Comment by saran-surya** [comment]
Hi @AnasAshir and @BryanLeong99 , Kindly drop in the Session name you have been using.

```dart
   EmailAuth.sessionName = "";
```

**Comment by BryanLeong99** [comment]
> Hi @AnasAshir and @BryanLeong99 , Kindly drop in the Session name you have been using.
> 
> ```dart
>    EmailAuth.sessionName = "";
> ```

EmailAuth.sessionName = "OTP Authentication";

**Comment by AnasAshir** [comment]
> Hi @AnasAshir and @BryanLeong99 , Kindly drop in the Session name you have been using.
> 
> ```dart
>    EmailAuth.sessionName = "";
> ```

EmailAuth.sessionName = "Tiedge";

**Comment by saran-surya** [comment]
Thanks, for the input. As the servers are now handling some enormous amount of loads, there might be an issue, currently working on a NODE JS plugin, that can be easily setup and be used HANDY with the package, Also will be trying to use the existing mailing package available in DART to make sure they are setup with EASE. And apologies for the inconvenience

**Comment by AnasAshir** [comment]
> Thanks, for the input. As the servers are now handling some enormous amount of loads, there might be an issue, currently working on a NODE JS plugin, that can be easily setup and be used HANDY with the package, Also will be trying to use the existing mailing package available in DART to make sure they are setup with EASE. And apologies for the inconvenience

How long till the servers are back online?

**Comment by saran-surya** [comment]
> > Thanks, for the input. As the servers are now handling some enormous amount of loads, there might be an issue, currently working on a NODE JS plugin, that can be easily setup and be used HANDY with the package, Also will be trying to use the existing mailing package available in DART to make sure they are setup with EASE. And apologies for the inconvenience
> 
> How long till the servers are back online?

Hopefully on 1st of next month.

**Comment by AnasAshir** [comment]
> > > Thanks, for the input. As the servers are now handling some enormous amount of loads, there might be an issue, currently working on a NODE JS plugin, that can be easily setup and be used HANDY with the package, Also will be trying to use the existing mailing package available in DART to make sure they are setup with EASE. And apologies for the inconvenience
> > 
> > 
> > How long till the servers are back online?
> 
> Hopefully on 1st of next month.

Okay. Thank You for your help.

**Comment by BryanLeong99** [comment]
> > > Thanks, for the input. As the servers are now handling some enormous amount of loads, there might be an issue, currently working on a NODE JS plugin, that can be easily setup and be used HANDY with the package, Also will be trying to use the existing mailing package available in DART to make sure they are setup with EASE. And apologies for the inconvenience
> > 
> > 
> > How long till the servers are back online?
> 
> Hopefully on 1st of next month.

Thank you very much for your effort.
