### ISSUE TITLE
Getting "OTP was not sent failure" again & again

### ISSUE THREAD

**Issue by arinagrawal05** [saran-surya/email_auth#14]
Hey, @saran-surya , hope you are well doing. i was using ur package email_auth package which is really appreciatable but getting same error (mentioned in title) in terminal console after sending some mails

**Comment by saran-surya** [comment]
Hi @arinagrawal05 , Thanks for the issue, I am currently working on a work around for the limits on the OTP, so will be fixing them, with a major release, 

Will Add some steps where you can host your own server with Heroku with just cloning a GitHub repository and moving forward to production.

And sorry for the inconvenience

**Comment by arinagrawal05** [comment]
its fine @saran-surya, I appreciate your work and just please update it ASAP... this package really meant to me-like developers :)

**Comment by Abhis2004** [comment]
How can I setup production server

**Comment by saran-surya** [comment]
> How can I setup production server

https://github.com/saran-surya/email_auth/issues/14#issuecomment-907034471
This will help you, else you can connect with me also for help.

**Comment by Abhis2004** [comment]
I'm getting this error while trying to send otp


D/ViewRootImpl@3080bffMainActivity: ViewPostIme pointer 0
D/ViewRootImpl@3080bffMainActivity: ViewPostIme pointer 1
I/flutter (27254): Email ID is valid
D/InputMethodManager(27254): SSI - flag : 0 Pid : 27254 view : com.carvaan.carvaan
D/InputMethodManager(27254): prepareNavigationBarInfo() DecorView@da74a5d[MainActivity]
D/InputMethodManager(27254): getNavigationBarColor() -855310
D/InputMethodManager(27254): SSI - flag : 0 Pid : 27254 view : com.carvaan.carvaan
D/InputMethodManager(27254): prepareNavigationBarInfo() DecorView@da74a5d[MainActivity]
D/InputMethodManager(27254): getNavigationBarColor() -855310
I/flutter (27254): --This error is from the package--
I/flutter (27254): FormatException: Unexpected character (at character 1)
I/flutter (27254):
I/flutter (27254): ^
I/flutter (27254): --End package error message--
D/InputMethodManager(27254): HSIFW - flag : 0 Pid : 27254
D/ViewRootImpl@3080bffMainActivity: MSG_RESIZED: frame=[0,0][1080,1920] ci=[0,63][0,0] vi=[0,63][0,0] or=1
D/ViewRootImpl@3080bffMainActivity: Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={true 3555448832} changed=false

**Comment by Abhis2004** [comment]
> > How can I setup production server
> 
> [#14 (comment)](https://github.com/saran-surya/email_auth/issues/14#issuecomment-907034471)
> This will help you, else you can connect with me also for help.

What I have to do after going to that link

**Comment by saran-surya** [comment]
Hi All,
The steps to setup the production server are mentioned here in a detailed way, Kindly have a look at it.

## https://saran-surya.github.io/email-auth-node/

**Comment by saran-surya** [comment]
Hi All, Kindly update the package, version 1.0.0 is out. And you can have a custom server with it 🚀

**Comment by babbaraniket** [comment]
Hey, I have followed all the steps in detail but I am unable to initialize the server. Can you please tell me what do I need to put in the server part of the remoteServerConfiguration? I have tried putting the address of my heroku app but it did not work.

var remoteServerConfiguration = {"server" : "____?___", "serverKey" : "______"};

Error Message-------
I/flutter (14693): email-auth >> Initialising Email-Auth server
I/flutter (14693): --- Package Error ---
I/flutter (14693): SocketException: Failed host lookup: '-------' (OS Error: No address associated with hostname, errno = 7)
I/flutter (14693): --- End Package Error ---
I/flutter (14693): --- package Error ---
I/flutter (14693): email-auth >> The remote server is not a valid.
I/flutter (14693): email-auth >> configured server : "-------"
I/flutter (14693): --- package Error ---

**Comment by babbaraniket** [comment]
Do you have any idea how can we change the template of the the email which is sent from Heroku server?

**Comment by saran-surya** [comment]
> Do you have any idea how can we change the template of the the email which is sent from Heroku server?

Hi @babbaraniket kindly create a new issue this is closed.

Thanks.
