### ISSUE TITLE
 FormatException: Unexpected character 

### ISSUE THREAD

**Issue by KaMing811** [saran-surya/email_auth#15]
hi @saran-surya  ,hope you have a good day. i am using your package email_auth ,its work until this afternoon. It said
I/flutter (17992): --This error is from the package--
I/flutter (17992): FormatException: Unexpected character (at character 1)
I/flutter (17992): <!DOCTYPE html>
I/flutter (17992): ^

in debug console

**Comment by Nugrahaz** [comment]
same issue after upgrade to latest flutter version and latest sdk (2.13.4)

**Comment by saran-surya** [comment]
Hi @Nugrahaz , @KaMing811 , The test server is currently overloaded with requests.
So they are currently working on it. The server will be back up on 31st July 12:00 am IST.

Also will be having a role out in the upcoming month will help people to host their own servers on any platforms they wish.
And there will also be a sponsor button to help in the continuous workflow of the test servers.

**Comment by vilakshan2996** [comment]
Still the issue is there bro

**Comment by saran-surya** [comment]
I hope now the issue is cleared as of now @vilakshan2996.

**Comment by saran-surya** [comment]
> same issue after upgrade to latest flutter version and latest sdk (2.13.4)

Hi @Nugrahaz , The issue is not because of the upgrade, it is because of the servers being overloaded

**Comment by saran-surya** [comment]
Hi All,
The steps to setup the production server are mentioned here in a detailed way, Kindly have a look at it.

## https://saran-surya.github.io/email-auth-node/

**Comment by saran-surya** [comment]
Hi All, Kindly update the package, version 1.0.0 is out. And you can have a custom server with it 🚀
