### ISSUE TITLE
Otp not sent

### ISSUE THREAD

**Issue by Abhis2004** [saran-surya/email_auth#16]
Whenever I'm trying to send Otp I'm getting this error  :-

D/ViewRootImpl@3080bff[MainActivity](27254): ViewPostIme pointer 0
D/ViewRootImpl@3080bff[MainActivity](27254): ViewPostIme pointer 1
I/flutter (27254): Email ID is valid
D/InputMethodManager(27254): SSI - flag : 0 Pid : 27254 view : com.carvaan.carvaan
D/InputMethodManager(27254): prepareNavigationBarInfo() DecorView@da74a5d[MainActivity]
D/InputMethodManager(27254): getNavigationBarColor() -855310
D/InputMethodManager(27254): SSI - flag : 0 Pid : 27254 view : com.carvaan.carvaan
D/InputMethodManager(27254): prepareNavigationBarInfo() DecorView@da74a5d[MainActivity]
D/InputMethodManager(27254): getNavigationBarColor() -855310
I/flutter (27254): --This error is from the package--
I/flutter (27254): FormatException: Unexpected character (at character 1)
I/flutter (27254): <!DOCTYPE html>
I/flutter (27254): ^
I/flutter (27254): --End package error message--
D/InputMethodManager(27254): HSIFW - flag : 0 Pid : 27254
D/ViewRootImpl@3080bff[MainActivity](27254): MSG_RESIZED: frame=[0,0][1080,1920] ci=[0,63][0,0] vi=[0,63][0,0] or=1
D/ViewRootImpl@3080bff[MainActivity](27254): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={true 3555448832} changed=false

**Comment by saran-surya** [comment]
Hi @Abhis2004,
The package is on an update, As we have tremendous server loads, the server will be down until 31st 12:00 am. and also with the new update you can set up a production server, to match your traffic needs, Sorry for the inconvenience, The update will be here soon.

**Comment by Abhis2004** [comment]
@saran-surya Thanks!
You made my life very easy. I will setup production server as soon as my app completes.

**Comment by saran-surya** [comment]
Hi All,
The steps to setup the production server are mentioned here in a detailed way, Kindly have a look at it.

## https://saran-surya.github.io/email-auth-node/

**Comment by saran-surya** [comment]
Hi All, Kindly update the package, version 1.0.0 is out. And you can have a custom server with it 🚀
