### ISSUE TITLE
OTP not sent!

### ISSUE THREAD

**Issue by Aqib-1998** [saran-surya/email_auth#17]
![issue](https://user-images.githubusercontent.com/88033913/131271728-0171e0bc-b6b8-4439-821d-aa6123a1c244.PNG)
getting this issue when trying to send OTP

**Comment by saran-surya** [comment]
Hi @Aqib-1998, The package is on an update, and the test servers are on high load, So thus Kindly wait until 31st 12:00 am. and after the update you will be able to set a custom production server to match your needs. Sorry for the inconvenience.

**Comment by Aqib-1998** [comment]
Aight, thanks alot for the reply .. A tutorial on setting up the server would be appreciated

**Comment by saran-surya** [comment]
Hi All,
The steps to setup the production server are mentioned here in a detailed way, Kindly have a look at it.

## https://saran-surya.github.io/email-auth-node/

**Comment by saran-surya** [comment]
Hi All, Kindly update the package, version 1.0.0 is out. And you can have a custom server with it 🚀
