### ISSUE TITLE
I/flutter (16741): Email ID is valid I/flutter (16741): --This error is from the package-- I/flutter (16741): FormatException: Unexpected character (at character 1) I/flutter (16741): <!DOCTYPE html> I/flutter (16741): ^ I/flutter (16741): --End package error message-- while sending otp

### ISSUE THREAD

**Issue by Ashifali777** [saran-surya/email_auth#18]

**Comment by saran-surya** [comment]
Hi @Ashifali777 , The package is on an update, Kindly requesting you to wait until 31st 12:00 am, And also the update will be out sooner. For more details kindly go through this issue

**Comment by saran-surya** [comment]
Hi All,
The steps to setup the production server are mentioned here in a detailed way, Kindly have a look at it.

## https://saran-surya.github.io/email-auth-node/

**Comment by saran-surya** [comment]
Hi All, Kindly update the package, version 1.0.0 is out. And you can have a custom server with it 🚀
