### ISSUE TITLE
Email ID is valid --This error is from the package-- XMLHttpRequest error. --End package error message--

### ISSUE THREAD

**Issue by macbethsoftwares** [saran-surya/email_auth#19]
Email ID is valid
--This error is from the package--
XMLHttpRequest error.
--End package error message--

**Comment by saran-surya** [comment]
> Email ID is valid
> --This error is from the package--
> XMLHttpRequest error.
> --End package error message--

Hi @macbethsoftwares  , The package is on an update, Kindly requesting you to wait until 31st 12:00 am, And also the update will be out sooner. For more details kindly go through this issue.

https://github.com/saran-surya/email_auth/issues/14

**Comment by saran-surya** [comment]
Hi All,
The steps to setup the production server are mentioned here in a detailed way, Kindly have a look at it.

## https://saran-surya.github.io/email-auth-node/

**Comment by saran-surya** [comment]
Hi All, Kindly update the package, version 1.0.0 is out. And you can have a custom server with it 🚀
