### ISSUE TITLE
Exception caught by Gesture

### ISSUE THREAD

**Issue by jayant246** [saran-surya/email_auth#2]
I am a creating an otp verification app through email. And I am using package: "email_auth 0.0.1+1.5". When I click on the button "Verify OTP" an error is shown in console :
EXCEPTION CAUGHT BY GESTURE
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'length' was called on null.
Receiver: null
Tried calling: length
**Main Problem is** : I have only seen 'true' in the console. But I haven't get 'otp sent' in the console which means otp is not sent to the target email.
Code: 
```
import 'package:flutter/material.dart';
import 'package:email_auth/email_auth.dart';

void main() => runApp(
  MaterialApp(home: HomePage(),
  theme: ThemeData.dark(),
  ),
);
class HomePage extends StatefulWidget {
  
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
   final TextEditingController _emailController = TextEditingController();
  final TextEditingController _otpController = TextEditingController();

  void sendOTP()async{
    EmailAuth.sessionName = "Temp name";
    var res = await (EmailAuth.sendOtp(recieverMail: _emailController.text));
    if(res) print('otp sent');
    else print('otp not sent');
  }

  void validateOTP(){
    var res = EmailAuth.validate(recieverMail: _emailController.text, userOTP: _otpController.text);
    if(res) {
    print('otp verified');
    }
    else {
      print('wrong otp');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextField(
              controller: _emailController,
              keyboardType: TextInputType.emailAddress,
              decoration: InputDecoration(
              ),
          ),
          TextField(
              controller: _otpController,
              decoration: InputDecoration(
                labelText: "Enter otp",
              ),
              keyboardType: TextInputType.number,
              obscureText: true,
          ),
          SizedBox(height: 20,),
          FlatButton(
            onPressed: () => sendOTP(),
            child: Text('Send OTP'),
          ),
          SizedBox(height: 20,),
          RaisedButton(
            onPressed: () => validateOTP(),
            child: Text('Verify OTP'),
          ),
          ],
        ),
      )
      );
  }
}
```
**When the exception was thrown, this was the stack:**
<img width="787" alt="Exception" src="https://user-images.githubusercontent.com/43151324/107324322-e81d3400-6acd-11eb-85e7-10674e1094d5.PNG">

**Comment by saran-surya** [comment]
Hello @jayant246 Kindly update to the latest version of the package **email_auth: ^0.0.1+1.8**

Also I suggest you to point the onPressed event directly to the function
```dart
 FlatButton(
            onPressed: sendOTP,
            child: Text('Send OTP'),
  ),
```
And also I am not getting errors that you get, so kindly hot restart your app, and also I have pasted the screenshot of the working app with your code, kindly refer it and here is my modification to your main.dart file, Try restarting your app and the issue is with the main.dart file and the listners,
```dart
import 'package:flutter/material.dart';
import 'package:email_auth/email_auth.dart';

void main() => runApp(
      MaterialApp(
        home: HomePage(),
        theme: ThemeData.dark(),
      ),
    );

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _otpController = TextEditingController();

  void sendOTP() async {
    EmailAuth.sessionName = "Temp name";
    var res = await (EmailAuth.sendOtp(receiverMail: _emailController.text));
    if (res)
      print('otp sent');
    else
      print('otp not sent');
  }

  void validateOTP() {
    var res = EmailAuth.validate(
        receiverMail: _emailController.text, userOTP: _otpController.text);
    if (res) {
      print('otp verified');
    } else {
      print('wrong otp');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          TextField(
            controller: _emailController,
            keyboardType: TextInputType.emailAddress,
            decoration: InputDecoration(),
          ),
          TextField(
            controller: _otpController,
            decoration: InputDecoration(
              labelText: "Enter otp",
            ),
            keyboardType: TextInputType.number,
            obscureText: true,
          ),
          SizedBox(
            height: 20,
          ),
          FlatButton(
            onPressed: sendOTP, ///Directly point the function (may save some time, if you do not have any pre processes)
            child: Text('Send OTP'),
          ),
          SizedBox(
            height: 20,
          ),
          RaisedButton(
            onPressed: validateOTP,///Directly point the function (may save some time, if you do not have any pre processes)
            child: Text('Verify OTP'),
          ),
        ],
      ),
    ));
  }
}
```
## Thanks for your valuable time 🥇 , kindly revert back if the issue persists, I will open the issue again 💯 
![successfully working](https://user-images.githubusercontent.com/59312489/107365303-9b078500-6b02-11eb-8b6c-6c57efe79a0c.jpg)

**Comment by jayant246** [comment]
When I try this app in my mobile device I get an OTP. But when I try with the emulator, this time the console shows 'Email is Valid'  only instead of that it must return 'Email is valid' & 'otp sent'. But when I try with the blank email the console shows 'Email is not valid' & 'otp not sent' . I don't understand what's the issue.
PS: I have tried with new project too.

**Comment by saran-surya** [comment]
@jayant246 as we have the email service on a dev server it might take up to 15 seconds for the process to happen, As the dev server must start and once that is done, the OTP will be sent, I have attached a video of it here, kindly check them and as stated the DEV server might take up to 15 secs for the boot once done, then we can have a faster service, so the initial first call might take time, but the rest will be faster, So I kindly request you to wait for some time for the process to suceed

**Comment by seljukmajid** [comment]
@saran-surya  hello I am new in flutter and I am trying to use the email_auth package for the verification but it's not working as it should. I am getting these error and I don't understand what am I doing wrong. please help me out will be very grateful thanks.   
![ss1](https://user-images.githubusercontent.com/50570024/196037551-dc94639e-a0e7-40e7-aa66-fa82f438a272.PNG)
![ss2](https://user-images.githubusercontent.com/50570024/196037562-ed60eb9f-4ccf-4774-8115-d729d96c1930.PNG)
![ss3](https://user-images.githubusercontent.com/50570024/196037569-4c9ff8c7-1b53-4fa8-a579-b9604a2afd7e.PNG)

**Comment by saran-surya** [comment]
> @saran-surya hello I am new in flutter and I am trying to use the email_auth package for the verification but it's not working as it should. I am getting these error and I don't understand what am I doing wrong. please help me out will be very grateful thanks. ![ss1](https://user-images.githubusercontent.com/50570024/196037551-dc94639e-a0e7-40e7-aa66-fa82f438a272.PNG) ![ss2](https://user-images.githubusercontent.com/50570024/196037562-ed60eb9f-4ccf-4774-8115-d729d96c1930.PNG) ![ss3](https://user-images.githubusercontent.com/50570024/196037569-4c9ff8c7-1b53-4fa8-a579-b9604a2afd7e.PNG)

Hi, did you seem to have a look at latest docs ?
The static members have been replaced. Please check documentation
