### ISSUE TITLE
Unable to access server

### ISSUE THREAD

**Issue by Abhis2004** [saran-surya/email_auth#21]
I/flutter (30573): --- Package Error ---
I/flutter (30573): Unable to access server. 😑
I/flutter (30573): --- End Package Error ---

Am I having this error cause I don't have remote server?

**Comment by saran-surya** [comment]
Hi @Abhis2004, The package has been updated. And the test server will be only up from tomorrow. And also the test server will have a mailing limit of 30 / per day. So to setup a production server, Kindly check this link

https://saran-surya.github.io/email-auth-node/ : This will guide you through the detailed steps of setting up a production server.

**Comment by saran-surya** [comment]
> I/flutter (30573): --- Package Error ---
> I/flutter (30573): Unable to access server. 😑
> I/flutter (30573): --- End Package Error ---
> 
> Am I having this error cause I don't have remote server?

The Error is because the test server is not available. It will be working from tomorrow.

**Comment by Abhis2004** [comment]
Thanks for the update
