### ISSUE TITLE
 OTP was not sent failure

### ISSUE THREAD

**Issue by arbaz-meo** [saran-surya/email_auth#22]
hi @saran-surya  your plugin is super for sending otp on email but from morning i cant send otp while my email is valid message show on  console "OTP not sent ".

**Comment by saran-surya** [comment]
Hi @arbaz-meo , Kindly share the screenshots of the error.

**Comment by saran-surya** [comment]
Hi @arbaz-meo , Are you still facing the issue ?

**Comment by arbaz-meo** [comment]
yeah still facing issue

**Comment by saran-surya** [comment]
Hi @arbaz-meo, The issue was fixed by 11pm yesterday, I am not sure if you have tried again, And please attach some screenshots and also what is the session name of the instance ?

**Comment by arbaz-meo** [comment]
It's working.

**Comment by arbaz-meo** [comment]
Thanks for the update.
