### ISSUE TITLE
Still using test server. Even after setting up custom server ?

### ISSUE THREAD

**Issue by macbethsoftwares** [saran-surya/email_auth#24]
email-auth >> Remote server is not available -- using test server --
email-auth >> ❗ Warning this is not reliable on production
email-auth >> The remote server configurations are valid
email-auth >> OTP sent successfully ✅

**Comment by macbethsoftwares** [comment]
Fixed.

**Comment by kentmartin12** [comment]
Hello, I have the same issue as you. May I know how do you solve this problem? Thanks

**Comment by saran-surya** [comment]
Thanks ✌️ happy coding

**Comment by saran-surya** [comment]
The solution is to pass in the config for the emailauth

Access the emailAuth.condig method
