### ISSUE TITLE
User not receiving otp

### ISSUE THREAD

**Issue by Abhis2004** [saran-surya/email_auth#25]
I can send otp successfully but the user not receiving the otp mail.

**Comment by saran-surya** [comment]
Kindly attach the screenshots of the debug console and the session Name, Are you using a custom server ? or the test server.

**Comment by kentmartin12** [comment]
Hi, I have this issue too, where the OTP is successfully sent, but I didn't receive the OTP in mail. And I use my custom server, but it seems the package said that I didn't have it. Here are the screenshots on my debug console, thank you very much!
![Screenshot 2021-09-03 163659](https://user-images.githubusercontent.com/53167038/131984687-a00c727a-0703-457d-9fa1-a6f348545700.png)

**Comment by saran-surya** [comment]
Hi,
So the issue is that you have to pass the relative path to the server,
lindly remove the last forward slash, and the remote server is set to go.

**Comment by saran-surya** [comment]
Hi @Abhis2004 , So is your issue resolved ?

**Comment by Abhis2004** [comment]
Yes sir my issue solved. Thanks!

**Comment by saran-surya** [comment]
Thanks, closing this issue.
