### ISSUE TITLE
Production server

### ISSUE THREAD

**Issue by Abhis2004** [saran-surya/email_auth#38]
Can you please make a video tutorial. How to setup production server please..

**Comment by saran-surya** [comment]
Hi @Abhis2004 , will surely look into it. 

Thanks

**Comment by Abhis2004** [comment]
@saran-surya Can u make the video tutorial under 1 week please?
I really need it please..

**Comment by saran-surya** [comment]
Hi @Abhis2004 , I will surely look into it, but under a week I am not sure if I will have the time for it. But will surely add them. And also if you follow the steps mentioned on this page you should be good to go. Kindly read the steps carefully.

https://saran-surya.github.io/email-auth-node/

**Comment by saran-surya** [comment]
> @saran-surya Can u make the video tutorial under 1 week please?
> I really need it please..

Also kindly tell me what issue are you facing actually ?

**Comment by Abhis2004** [comment]
C:\Users\araj8\Downloads\email_otp_verification-main>npx email-auth-node --generate

        email-auth-node >> The HTML has missing parameters

--- package Error ---
Error: Run Time Error
    at C:\Users\araj8\Downloads\email_otp_verification-main\bin\cli.js:107:23
    at new Promise (<anonymous>)
    at verifyHTML (C:\Users\araj8\Downloads\email_otp_verification-main\bin\cli.js:97:12)
    at main (C:\Users\araj8\Downloads\email_otp_verification-main\bin\cli.js:218:23)
    at Object.<anonymous> (C:\Users\araj8\Downloads\email_otp_verification-main\bin\cli.js:228:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
--- package Error ---

email-auth-node >> (ERROR) : Run Time Error
email-auth-node >> Error from package, Kindly raise an issue here

<===========                HERE IS MY HTML FILE         ==================>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OTP</title>
    <link rel="stylesheet" href="./style.css"> 
    
</head>
<body>
        <div class='p-14 rounded-md m-2  bg-yellow-400 text-black text-xl w-screen'>
            Please find your OTP for logging into <b> {Carvaan} </b>
            <br/>
            <br/>
            <span class="text-2xl font-bold">
                {OTP}
            </span>
        </div>
</body>
</html>

**Comment by Abhis2004** [comment]
I sent my html file as you asked.

**Comment by saran-surya** [comment]
> I sent my html file as you asked.

Answered 🙌
