### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by GJJ2019** [saran-surya/email_auth#4]
This is a request to add support for null safety to package:email_auth.

**Comment by GJJ2019** [comment]
checkout PR #3

**Comment by saran-surya** [comment]
Thankyou for your valuable time, I am reviewing the code, and will be merging them as soon as possible 👍🏻

**Comment by saran-surya** [comment]
Thankyou for the changes @GJJ2019 , The request has been merged 💯

**Comment by saran-surya** [comment]
@GJJ2019 Kindly rebase with the latest master before any new changes..
