### ISSUE TITLE
Remote server is not available -- using test server --

### ISSUE THREAD

**Issue by nooraldin** [saran-surya/email_auth#49]
hello
I get the error message

```
I/flutter ( 2876): email-auth >> Remote server is not available -- using test server --
I/flutter ( 2876): email-auth >> ❗ Warning this is not reliable on production
I/flutter ( 2876): --- Package Error ---
I/flutter ( 2876): Unable to access server. 😑
I/flutter ( 2876): --- End Package Error ---
```

my code is
```

import 'package:email_auth/email_auth.dart';

  TextEditingController _email = new TextEditingController();
  TextEditingController _otp = new TextEditingController();


  bool showtime = false;
  double loaderSize = 100;
  int _counter = 3;
  late Timer _timer;
  late EmailAuth emailAuth;
  bool submitValid = false;



@override
  void initState() {
  emailAuth =  new EmailAuth(sessionName: "Sample session");
    super.initState();
  }


  void verifyOTP() {
  var res = emailAuth.validateOtp(
    recipientMail: _email.value.text,
    userOtp: _otp.value.text);
    print(emailAuth.validateOtp(
        recipientMail: _email.value.text,
        userOtp: _otp.value.text));
    if (res) {
      print("OTP Verified");
    }else{
      print("Invalid OTP");
  }

  }

  void sendOTP() async {
    bool result = await emailAuth.sendOtp(
        recipientMail: _email.value.text, otpLength: 5);
    if (result) {
      setState(() {
        submitValid = true;
      });
    }
  }



```

**Comment by saran-surya** [comment]
Hi @nooraldin , it is because you are using a test server. Kindly setup a production server for better performance and reliability..

This will help you further.

https://github.com/saran-surya/email_auth/issues/14#issuecomment-907034471

**Comment by nooraldin** [comment]
thanks for your answer but do you mean i have to add this 

```
emailAuth.config(remoteServerConfiguration);

// remoteServerConfiguration : Signature
{
  "server": "server url",
  "serverKey": "serverKey"
}
```
can I get it when I use Androidtest Emulator with local server (XAMPP-Apache) to test the App,
There is only one old video on YouTube that did not have to use a server!
https://www.youtube.com/watch?v=zO1D-lzI3m0&t=1s&ab_channel=Codepur
but it is working in old version mailer 0.0.1

thanks

**Comment by saran-surya** [comment]
> thanks for your answer but do you mean i have to add this
> 
> ```
> emailAuth.config(remoteServerConfiguration);
> 
> // remoteServerConfiguration : Signature
> {
>   "server": "server url",
>   "serverKey": "serverKey"
> }
> ```
> 
> can I get it when I use Androidtest Emulator with local server (XAMPP-Apache) to test the App, There is only one old video on YouTube that did not have to use a server! https://www.youtube.com/watch?v=zO1D-lzI3m0&t=1s&ab_channel=Codepur but it is working in old version mailer 0.0.1
> 
> thanks

Yes you have to do that, I will be starting a youtube channel soon for the purpose. Will let you know soon. For now please follow the instructions in the email_auth_node GitHub pages
