### ISSUE TITLE
https://app-authenticator.herokuapp.com/dart/auth/${recipientMail}?CompanyName=${this.sessionName} not returning proper response

### ISSUE THREAD

**Issue by ParthPandey2236** [saran-surya/email_auth#52]
The above API provided is not returning the proper responce

**Comment by saran-surya** [comment]
Hi @ParthPandey2236  , it is because you are using a test server. Kindly setup a production server for better performance and reliability..

This will help you further. Please bread the docs ✌🏼

https://github.com/saran-surya/email_auth/issues/14#issuecomment-907034471
