### ISSUE TITLE
: --- Package Error ---

### ISSUE THREAD

**Issue by shah000** [saran-surya/email_auth#57]
I/flutter (11341): email-auth >> Initialising Email-Auth server
I/flutter (11341): email-auth >> Remote server is not available -- using test server --
I/flutter (11341): email-auth >> ❗ Warning this is not reliable on production
I/flutter (11341): --- Package Error ---
I/flutter (11341): SocketException: Failed host lookup: 'app-authenticator.herokuapp.com' (OS Error: No address associated with hostname, errno = 7)
I/flutter (11341): --- End Package Error ---
I/flutter (11341): not send

**Comment by saran-surya** [comment]
Hi @shah000 , The test server is under a refresh period, Kindly set up a production server for un-interrupted performance and better reliability.
<hr/>

### This should help you get started
[https://saran-surya.github.io/email-auth-node/](https://saran-surya.github.io/email-auth-node/)

Thanks
