### ISSUE TITLE
--- Package Error ---

### ISSUE THREAD

**Issue by adarsh-kn** [saran-surya/email_auth#58]
I/flutter (20214): email-auth >> Initialising Email-Auth server
I/flutter (20214): email-auth >> Remote server is not available -- using test server --
I/flutter (20214): email-auth >> ❗ Warning this is not reliable on production
I/flutter (20214): email-auth >> The remote server configurations are valid
I/flutter (20214): --- Package Error ---
I/flutter (20214): Unable to access server. 😑
I/flutter (20214): --- End Package Error ---

I have set up a production server following the instructions... still getting this error. Please let me know why.

Thanks in advance!

**Comment by saran-surya** [comment]
Hi @adarsh-kn , this is due to the refresh period in test servers, please refer this issue. Also you can set up a production server for a better reliable connection.

https://github.com/saran-surya/email_auth/issues/57#issuecomment-1003404033

# Setting up a production server
https://saran-surya.github.io/email-auth-node/

**Comment by adarsh-kn** [comment]
Hey @saran-surya ,

I have already setup the production server following those steps mentioned in https://saran-surya.github.io/email-auth-node/

I am still getting an error as shown above. 

I/flutter (20214): email-auth >> The remote server configurations are valid

This line confirms that my remote server configurations are valid.

I/flutter (20214): --- Package Error ---
I/flutter (20214): Unable to access server. 😑
I/flutter (20214): --- End Package Error ---

But I am getting this error. Don't know why

**Comment by saran-surya** [comment]
Can you please only post the remote server url ?

**Comment by adarsh-knn** [comment]
https://bmsce-foodies.herokuapp.com/

I set up the production server just yesterday.

**Comment by adarsh-kn** [comment]
https://bmsce-foodies.herokuapp.com/

I set up the production server just yesterday.

**Comment by saran-surya** [comment]
> https://bmsce-foodies.herokuapp.com/
> 
> I set up the production server just yesterday.

Yes the remote server is working, can you please post the heroku logs ?

**Comment by saran-surya** [comment]
Hi @adarsh-kn Is your issue resolve ?

**Comment by adarsh-kn** [comment]
Heyy @saran-surya ,
Everything is working perfectly fine now.
Please don't mind me for replying a bit late.
Really appreciate your quick support. 💯

**Comment by saran-surya** [comment]
Hello @adarsh-kn , thankyou. Have a great day✌🏽

**Comment by rahulrajamani31** [comment]
sir iam also facing the same error my  production server link is working properly .........
----->https://emailauthserver.herokuapp.com/

But when i use this in my flutter code it showing the below error..

email-auth >> Initialising Email-Auth server
--- Package Error ---
Unable to access remote server. 😑
--- End Package Error ---
--- package Error ---
email-auth >> The remote server is not a valid.
email-auth >> configured server : "[https://emailauthserver.herokuapp.com/]()"
--- package Error ---
