### ISSUE TITLE
otp sending failed 

### ISSUE THREAD

**Issue by aqib19980000** [saran-surya/email_auth#6]
it was working fine before today.. today when i was adding some new features to my app, it is not working. the otp is not sending to the email 
please help !

**Comment by aqib19980000** [comment]
![Screenshot_1619113096](https://user-images.githubusercontent.com/83029379/115761159-790c6780-a3bb-11eb-9d7c-ba5367aeadd2.png)

**Comment by aqib19980000** [comment]
void sendOtp()async{

    ///Accessing the EmailAuth class from the package
    EmailAuth.sessionName = "Sample";
    ///a boolean value will be returned if the OTP is sent successfully

      var data = await EmailAuth.sendOtp(
          receiverMail: _emailEditingController.text);

    if(data){
      final snackBar = SnackBar(content: Text('OTP has been sent. Please check your email!'));
       ScaffoldMessenger.of(context).showSnackBar(snackBar);
      _OTP = true;
      _updateSetState();
    }else{
      final snackBar = SnackBar(content: Text('OTP sending failed!'));
      ScaffoldMessenger.of(context).showSnackBar(snackBar);
    }
  }





otp sending failed is executing always

**Comment by saran-surya** [comment]
Hello @aqib19980000 , The package is stable beta, and it is working fine, I have tested them and also there are many active sessions going on, Kindly check your code. If you are still facing the issue kindly revert back. Else I will close the issue by 25/04/2021

Thanks
