### ISSUE TITLE
not able to send the email to the user I think it is some at the end of the gmail earlier it was working fine

### ISSUE THREAD

**Issue by Silent-faith** [saran-surya/email_auth#65]

**Comment by Silent-faith** [comment]
solved

**Comment by saran-surya** [comment]
Hi @Silent-faith , Can you please mention what your issue was, it will be helpful for the people who have the same issue in the future.

**Comment by Silent-faith** [comment]
hi saran the issue was that the gmail was saying the login as a suspicious  when the email auth was login so I changed my password again the problem was solved.
