### ISSUE TITLE
UI changes required for the OTP emails sent.

### ISSUE THREAD

**Issue by crankyvein** [saran-surya/email_auth#7]
If we send email varification then author names appears in email verification mail. It is not good for UX for an app so please remove author name.

**Comment by saran-surya** [comment]
Hello @crankyvein, 
Yes will be working on the update, and also will be improving the UI for the mail. Also I can remove my name but the package name will be present, as this is all taken care by my server for free, thus I will make the best to make sure the UI is much better.

**Comment by saran-surya** [comment]
Closing this issue, Current changes made to UI 
![image](https://user-images.githubusercontent.com/59312489/118388661-6ba56e80-b643-11eb-9534-1aacb9cefceb.png)

<br>
Thankyou for the issue. 👍🏻
