### ISSUE TITLE
OTP SEND but not received.

### ISSUE THREAD

**Issue by PickappJhay** [saran-surya/email_auth#73]
Hi, I'm using some e-mail from go-daddy and successfully changed the SMTP server.
The problem is whenever I click send It will return true value on flutter means that the process is successful.
I don't know why I can't receive an OTP.

here's the heroku logs.

![image](https://user-images.githubusercontent.com/94879668/185784116-82558a99-8e54-4db8-876c-76810a57f720.png)

**Comment by PickappJhay** [comment]
This is fixed. just some tweeks at mailer.py

**Comment by rt234cw** [comment]
@PickappJhay 
Hi, did you mean you use godaddy instead of heroku??  
if so, could you share how to do that??
