### ISSUE TITLE
Package Error Unable to access server. 😑, Test server is also not working now!

### ISSUE THREAD

**Issue by RajulSahu** [saran-surya/email_auth#75]
I tried to set up the production server, it was not working, so I switched again to test server, but it is also now working now. I double checked everything and the code is same as it was before in working condition for the test server, Please help!!!
Screen Shot:
![error](https://user-images.githubusercontent.com/74370799/195999032-b7c96579-4e88-49c3-b080-d3a24b0d180c.PNG)

**Comment by saran-surya** [comment]
Yes, there is a plan to shutdown all test servers, so the quotas has been completely reduced. People have been using it for granted, so sorry for the quota change. The production server patch will soon be made. Apologies for the delay

**Comment by RajulSahu** [comment]
Thanks for the reply,
I have setup the server fully, but as you know Google has removed less secured apps feature, and the server was using gmail service so please provide instructions on how to apply the patch after you release it, so that it could be easy to set it up again.
I was using this package in my college project, it was working before but when I presented the app in front of my professors, it stopped working from then and I felt very bad, please try and provide the patch as soon as possible so I could present it again in working condition.
Thanks again.

**Comment by saran-surya** [comment]
Can you please contact me through LinkedIn or Insta, I will help you setup the patch for prod server. The planned release is postponed to NOV.

**Comment by RajulSahu** [comment]
yes sir sure...

**Comment by RajulSahu** [comment]
could you please share any one of your handle?

**Comment by saran-surya** [comment]
Test servers are back online, Kindly use them
