### ISSUE TITLE
Unable to access server

### ISSUE THREAD

**Issue by SENSEI54** [saran-surya/email_auth#79]
i am using email_auth for my college project(Messaging app) using flutter and now getting error of unable to access server error so @saran-surya please help ASAP!

error showing 
I/flutter ( 5699): email-auth >> Remote server is not available -- using test server --
I/flutter ( 5699): email-auth >> ❗ Warning this is not reliable on production
I/flutter ( 5699): --- Package Error ---
I/flutter ( 5699): Unable to access server. 😑
I/flutter ( 5699): --- End Package Error ---

**Comment by saran-surya** [comment]
Hi @sensei54, 
Kindly go through the documentation, I have stopped all test servers. And kindly requesting you to setup a production server with outlook email as an option as Google has disabled less secure apps, also if it's for a college project and you can host the server somewhere do let me know there is an alternative approach available. With GCP, we can make is feasible based on your project deadline

**Comment by saran-surya** [comment]
Hi @sensei54, 
Kindly go through the documentation, I have stopped all test servers. And kindly requesting you to setup a production server with outlook email as an option as Google has disabled less secure apps, also if it's for a college project and you can host the server somewhere do let me know there is an alternative approach available. With GCP, we can make is feasible based on your project deadline

**Comment by saran-surya** [comment]
Hi @sensei54, 
Kindly go through the documentation, I have stopped all test servers. And kindly requesting you to setup a production server with outlook email as an option as Google has disabled less secure apps, also if it's for a college project and you can host the server somewhere do let me know there is an alternative approach available. With GCP, we can make is feasible based on your project deadline

**Comment by saran-surya** [comment]
MARKING AS STALE DUE TO INACTIVITY,

Kindly feel free to comment and I will reopen the issue.
