### ISSUE TITLE
Feature request for OTP length.

### ISSUE THREAD

**Issue by isarojdahal** [saran-surya/email_auth#8]
Instead of sending six digit OTP code to mail, there should be option or params to set length for OTP. Let's say having OTP code of 4 digit is easier for user to remember and type it into the app or sometimes 5..

**Comment by saran-surya** [comment]
Hi @isarojdahal , Yes this is a valid point.
Will surely start working on it. 

Thanks for the issue

**Comment by isarojdahal** [comment]
Thank you for the kind consideration. I believe that this package has a lot of potential in future days. <3

**Comment by saran-surya** [comment]
Hi @isarojdahal , The feature has been included in the latest version, for the production servers.
Thankyou for your inputs 🚀

**Comment by isarojdahal** [comment]
Thankyou so much for the update <3 .
