### ISSUE TITLE
Validation Failure ❌

### ISSUE THREAD

**Issue by Astaxask** [saran-surya/email_auth#85]
I have everything set up for the production server. However, when I try to validate the OTP it always fails.

<img width="719" alt="Screen Shot 2023-03-02 at 4 05 43 PM" src="https://user-images.githubusercontent.com/112664126/222570320-694c9de8-b9a9-49ab-b5e4-1f1544ced21d.png">

It does seem that the issue is from the if statement below. It cannot validate the statement `(_finalOTP == userOtp)`

<img width="442" alt="Screen Shot 2023-03-02 at 5 23 37 PM" src="https://user-images.githubusercontent.com/112664126/222586487-8266f52c-4cdf-4376-963b-4a778a7d3cc6.png">
<img width="407" alt="Screen Shot 2023-03-02 at 5 23 19 PM" src="https://user-images.githubusercontent.com/112664126/222586877-c39aeaf9-ad88-4a3b-8eb7-4f73fb885d70.png">

When I change the statement to `(_finalEmail.trim() == recipientMail.trim())` only, I have no issue.
<img width="442" alt="Screen Shot 2023-03-02 at 5 28 39 PM" src="https://user-images.githubusercontent.com/112664126/222587365-b911d405-d427-499b-9ff4-f238c268d763.png">
<img width="442" alt="Screen Shot 2023-03-02 at 5 28 48 PM" src="https://user-images.githubusercontent.com/112664126/222587377-0d179704-2cc5-4a1b-9ff5-367f0b36bc68.png">

Please help!

**Comment by saran-surya** [comment]
Hi, @Astaxask 
That actually seems weird, changing the OTP verification condition makes no use in this case. Can you post the code that you are using in your home page ? Because I have been able to work with it till date.

Can you try using the example from the repo ? Or post your code of the HomeScreen where you set the values of the settings. Also if the ```_finalEmail == recipientMail``` This should work as expected only.

**Comment by Astaxask** [comment]
It works!!! I just copied the code from the example in the pub.dev email_auth and it worked!

Thank you! I was trying a complex UI design and maybe it messed up the logic.
