### ISSUE TITLE
Parse trailing xxx..../ in the server url configuration

### ISSUE THREAD

**Issue by saran-surya** [saran-surya/email_auth#90]
**Trailing ```/``` in the server url configuration file**
The trailing ```/``` in the server url is causing a breaking change.

## REFERENCE
https://github.com/saran-surya/email_auth/issues/89#issuecomment-1643211350

**Comment by soueip** [comment]
<img width="574" alt="sssssssssss" src="https://github.com/saran-surya/email_auth/assets/71385302/36597e9b-a94e-4a2d-9fda-2d34f36b6c8a">

**Comment by saran-surya** [comment]
Hi @soueip ,
Can you please explain the last comment from your side ?
